= Create a Passive Discovery
:description: Learn how to identify network inventory with OpenNMS Lōkahi/Cloud using Syslog and SNMP traps (passive discovery).

A xref:get-started/discovery/introduction.adoc#passive-discovery[passive discovery] is one method to identify the devices on your network and add them to your monitoring inventory.
You may also choose to xref:get-started/discovery/active.adoc[create an active discovery].

NOTE: Passive discovery works only with Minions running on Linux.

You can create only one passive discovery:

. Choose *Discovery* in the left navigation menu.
. On the Discovery page, click *Add Discovery*.
. In the Passive Discovery area, toggle *SYSLOG & SNMP TRAPS* on.
. Fill in the appropriate information in each field.
+
NOTE: To create xref:inventory/nodes.adoc#tag-create[tags], click the drop-down arrow in the *Search/Add tags* field, type a name for the tag, and click *New*.

. Click *Save Discovery*.

The name of the passive discovery you created appears in the My Passive Discoveries list.
Click the *toggle on* button to perform discovery on the selected node.