
:imagesdir: ../assets/images
:!sectids:

= Alerts

Alerts are representations of potential and actual problems in your monitored network.
Your environment's xref:policies/introduction.adoc[monitoring policies] define the conditions under which alerts are generated.

The https://github.com/OpenNMS-Cloud/lokahi/wiki/Insights-Dashboard[Insights Dashboard] displays a summary of alerts over a selected period of time.
For more detailed insights into your network's alerts, including the monitoring policies that defined them, select *Alerts List* in the left navigation menu.

For information about severities, see https://github.com/OpenNMS-Cloud/lokahi/wiki/Alert-Severities[Alert Severities].

_**Benefits:** You do not have to sift through a lot of information to see which nodes require attention; you can simply review alerts of different severities._

== Before you begin

Before Lōkahi begins generating alerts, you must configure the following:

* Your xref:discovery/introduction.adoc[network discovery] settings.
* (Optional) At least one monitoring policy.
** If you do not want to configure a policy immediately, you can use the xref:policies/introduction.adoc#default-monitoring-policy[default monitoring policy] instead.