
= Manage Alerts
:description: Learn how to search, filter, acknowledge, and resolve alerts, and how to test nodes affected by alerts.

You can manage your network's alerts on the *Alerts Table* page.
(Select **Alerts** in the left navigation menu.)

== Search

You can search for specific text in alerts.
To do so, type your search term in the *Search Alerts* box.

== Filter

You can filter alerts by severity and by time span.

To filter alerts by severity, select a severity (for example, *Major*) from the list at the top of the page.
The associated alerts are displayed.

To filter alerts by time span, select an option from the time filter settings (for example, *7D*).
The alerts that occurred over the specified time period are displayed.
By default, the page displays alerts that occurred within the last 24 hours.

=== Clear filters

To clear any filters on your alerts, click *Clear All Filters*.
The alerts list displays all alerts.

== Acknowledge an alert

To acknowledge an alert, find the alert that you want to acknowledge and select the *Acknowledge* symbol beside its creation time.

An alert is acknowledged when the symbol is green with a white check.
An alert is unacknowledged when the symbol is white with a green outline and check.

// Resolve an alert topic

//<steps to resolve an alert>

== Test affected node

Follow these steps to test a node affected by an alert:

. Find the alert whose affected node you want to test.
. Click the *Expand* symbol to show the alert's details.
. Select *Run Test*.
The node's status (*Degraded*, *Success*, and so on) is displayed.

// <these instructions will be updated in the future, when the process is closer to finalized>