
= Manage Monitoring Policies
:description: Learn how to edit a monitoring policy in OpenNMS Lōkahi/Cloud.

You can edit or delete any monitoring policy, except for the default one.

With the default policy, you can only add or remove tags.
To turn off the default monitoring policy, remove the tag(s) associated with it.

== Edit a monitoring policy

Follow these steps to edit a monitoring policy:

. Click **Monitoring Policies** in the left navigation menu.
. Select a policy from the **Existing Policies** list.
. Update the policy's configuration settings as desired.
. Click on any associated rules to update configuration settings as desired, if applicable.
. Click **Save Rule** (if you edited a rule) and **Save Policy**.

The policy's configuration settings are updated.

== Delete a monitoring policy

When you delete a monitoring policy, all associated alerts will be removed.
Before deletion, a prompt appears that details the number of associated alerts, to confirm you want to proceed.

Note that you cannot delete the default monitoring policy.

Follow these steps to delete a monitoring policy:

. Click **Monitoring Policies** in the left navigation menu.
. Select a policy from the **Existing Policies** list.
. Click the *delete* symbol on the top right of the *Policy Name* area.
. Click *Delete* to confirm deletion.



