/*
 * Licensed to The OpenNMS Group, Inc (TOG) under one or more
 * contributor license agreements.  See the LICENSE.md file
 * distributed with this work for additional information
 * regarding copyright ownership.
 *
 * TOG licenses this file to You under the GNU Affero General
 * Public License Version 3 (the "License") or (at your option)
 * any later version.  You may not use this file except in
 * compliance with the License.  You may obtain a copy of the
 * License at:
 *
 *      https://www.gnu.org/licenses/agpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.  See the License for the specific
 * language governing permissions and limitations under the
 * License.
 */
package org.opennms.horizon.events.xml;

// ---------------------------------/
// - Imported classes and packages -/
// ---------------------------------/

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;

/**
 * Class Header.
 *
 * @version $Revision$ $Date$
 */
@XmlRootElement(name = "header")
@XmlAccessorType(XmlAccessType.FIELD)
// @ValidateUsing("event.xsd")
public class Header implements Serializable {
    private static final long serialVersionUID = 1963826810463701325L;

    // --------------------------/
    // - Class/Member Variables -/
    // --------------------------/

    /**
     * Field _ver.
     */
    @XmlElement(name = "ver")
    private String _ver;

    /**
     * Field _dpName.
     */
    @XmlElement(name = "dpName")
    private String _dpName;

    /**
     * The time at which this log was generated. The time
     *  is in the format generated by the java.text.DateFormat
     * using the
     *  DateFormat.FULL style for the default locale. For example:
     *  "Monday, February 18, 2002 3:01:58 PM EST"
     */
    @XmlElement(name = "created")
    private String _created;

    /**
     * Field _mstation.
     */
    @XmlElement(name = "mstation")
    private String _mstation;

    // ----------------/
    // - Constructors -/
    // ----------------/

    public Header() {
        super();
    }

    // -----------/
    // - Methods -/
    // -----------/

    /**
     * Returns the value of field 'created'. The field 'created'
     * has the following description: The time at which this log
     * was generated. The time
     *  is in the format generated by the java.text.DateFormat
     * using the
     *  DateFormat.FULL style for the default locale. For example:
     *  "Monday, February 18, 2002 3:01:58 PM EST"
     *
     * @return the value of field 'Created'.
     */
    public String getCreated() {
        return this._created;
    }

    /**
     * Returns the value of field 'dpName'.
     *
     * @return the value of field 'DpName'.
     */
    public String getDpName() {
        return this._dpName;
    }

    /**
     * Returns the value of field 'mstation'.
     *
     * @return the value of field 'Mstation'.
     */
    public String getMstation() {
        return this._mstation;
    }

    /**
     * Returns the value of field 'ver'.
     *
     * @return the value of field 'Ver'.
     */
    public String getVer() {
        return this._ver;
    }

    /**
     * Sets the value of field 'created'. The field 'created' has
     * the following description: The time at which this log was
     * generated. The time
     *  is in the format generated by the java.text.DateFormat
     * using the
     *  DateFormat.FULL style for the default locale. For example:
     *  "Monday, February 18, 2002 3:01:58 PM EST"
     *
     * @param created the value of field 'created'.
     */
    public void setCreated(final String created) {
        this._created = created;
    }

    /**
     * Sets the value of field 'dpName'.
     *
     * @param dpName the value of field 'dpName'.
     */
    public void setDpName(final String dpName) {
        this._dpName = dpName;
    }

    /**
     * Sets the value of field 'mstation'.
     *
     * @param mstation the value of field 'mstation'.
     */
    public void setMstation(final String mstation) {
        this._mstation = mstation;
    }

    /**
     * Sets the value of field 'ver'.
     *
     * @param ver the value of field 'ver'.
     */
    public void setVer(final String ver) {
        this._ver = ver;
    }

    @Override
    public String toString() {
        return new OnmsStringBuilder(this).toString();
    }
}
