
= Network Inventory
:description: Overview of network inventory in OpenNMS Lōkahi/Cloud, including monitored, unmonitored, and detected nodes.

Inventory refers to the devices and entities in your network that OpenNMS Cloud has identified through the xref:get-started/discovery/introduction.adoc[discovery] process.
OpenNMS displays these nodes on the *Network Inventory* page under the following categories:

* *Monitored Nodes*: Discovered nodes that OpenNMS Cloud is monitoring.
* *Unmonitored Nodes*: Discovered nodes that are not yet tagged for monitoring.
They did not match any of the criteria in any monitoring policy, including the xref:get-started/policies/introduction.adoc#default-monitoring-policy[default one].
* *Detected Nodes*: Nodes identified through an indirect way like via flow.
You can choose to monitor the node through a xref:get-started/policies/introduction.adoc[monitoring policy], or ignore it.

Inventory management involves the following:

* Examining unmonitored and detected nodes to determine if you want to monitor them.
* xref:inventory/nodes.adoc#tag-create[Tagging] nodes so that they are monitored.
* xref:get-started/policies/manage.adoc[Updating] or xref:get-started/policies/create.adoc[creating] monitoring policies to discover additional network nodes.
* https://github.com/OpenNMS-Cloud/lokahi/wiki/Manage-nodes#remove-nodes-you-do-not-want-to-monitor[Removing nodes] you do not want to monitor from the monitored nodes list.