spring:
  application:
    name: lokahi-alert

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/alert
    username: alert
    password: passw0rd

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: db/changelog/changelog.xml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "alert-service"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

keycloak:
  realm: opennms
  base-url: http://onms-keycloak:8080/auth
  public-key: ""

grpc:
  server:
    port: 6565
    deadline: 60000

kafka:
  topics:
    trap-event: "events"
    tag-operation: "tag-operation"
    alert: "alerts"
    monitoring-policy: "monitoring-policy"
    node-changed: "node"
    internal-event: "internal-event"
    threshold-rules: "metrics-threshold-rules"
    threshold-events: "metrics-threshold-event"
    create-topics:
      enabled: true
      alert:
        name: "alerts"
      monitoring-policy:
        name: "monitoring-policy"
      threshold-rules:
        name: "metrics-threshold-rules"
      node-changed:
        name: "node"
        partitions: 1 # topic relies on there being a single partition for ordering

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
