
= Minion Management
:description: Learn how to manage data collectors (Minions) in OpenNMS Cloud/Lōkahi, including how to add a location, review flows and events, and remove a location.

A Minion is a lightweight, secure collector that monitors and communicates with the devices on your network, shares collected data, and connects your network with OpenNMS Cloud/Lōkahi.

With OpenNMS Cloud, you install your first Minion as part of the onboarding process.

Each Minion is associated with a monitoring location.
The monitoring location defines a network area where you installed your Minion (for example, Boston, Building 3).
The Minion installed as part of onboarding belongs to the "default" location.
The Minion's security certificate is closely tied to the location.

This section describes management tasks for installed Minions, and how to deploy a Minion from the UI.

[[create-location]]
== Create a location
A location defines the network area where you installed your Minion.

Note that specifying a physical address for the location is optional; if you do, the nodes associated with the location will appear on the map page.
See xref:visualizations/introduction.adoc#geo-map[Geographical Map] in the visualizations chapter.

. Click *Locations* in the left navigation menu.
. Click the *+ Location* button.
. Type the location name in the field.
+
Note that you cannot edit the location name after you save the location.
. Click *Save*.

The new location is saved.
From the Locations list, you can edit the location (to add a Minion to it) or delete it.

== Deploy a Minion
To deploy a Minion, you need to download the software bundle and install it locally.
The bundle includes the following:

* An encrypted Minion certificate with a decryption password
* A Docker Compose file with a Minion container

Deployment can take up to 10 minutes.

=== Requirements

Make sure your system meets the following requirements:

* CPU: 3GHz quad core x86_64 and above
* RAM: 8GB (physical) and above
* Storage (disk space): 100GB with SSD and above
* Docker environment with Docker Compose (installation instructions: https://docs.docker.com/desktop/install/mac-install/[Mac], https://docs.docker.com/desktop/install/linux-install/[Linux], https://docs.docker.com/desktop/install/windows-install/[Windows])
* Access to a terminal window or command line interface
* Synchronized system time (via NTP or Windows time service)

NOTE: We recommend using Linux for production environments.
Mac and Windows work as test environments for the Minion, but sending traps to the Minion does not work correctly.
Traps will not be associated with the correct node, and xref:get-started/discovery/introduction.adoc#passive-discovery[passive discovery] will not be able to find the node that is sending traps.

To deploy a Minion, follow these steps:

. Click *Locations* in the left navigation menu.
. In the *Locations* list, click the vertical ellipsis (*⋮*) next to the location where you want to deploy the Minion.
. Click *Edit*.
+
NOTE: You can also deploy a Minion when you create a new location.
Click *+Location*, fill in the fields, and click *Save*, and follow the steps in the rest of this procedure.
. Click *Download Bundle*.
. Create a permanent directory for the Minion on the device where you want to run it.
. Copy the downloaded bundle to the permanent directory and unzip it.
. Open a terminal window, navigate to the bundle location, and type the following command: `docker compose up -d`.
. In the OpenNMS UI, click *Save*.

Your Minion will appear in the Locations screen once it is running and OpenNMS detects it.

// do they click save after the Minion has been discovered or will it show up in the UI when it's been detected?

== Regenerate a Minion certificate
If at any point you are concerned your Minion might have been compromised, you may want to revoke the Minion's current security certificate and create a new one for it.

To regenerate a Minion certificate, follow these steps:

. Click *Locations* in the left navigation menu.
. In the *Locations* list, click the vertical ellipsis (*⋮*) next to the location with the Minion whose certificate you want to revoke and recreate.
. Click *Edit*.
. Click the *Regenerate* button.
. When prompted, click *Continue*.
. Click *Save*.

//is there anything else they need to do when they regenerate a certificate? Does the Minion reboot or do anything which might result in a gap in monitoring? I'd like to tell the users.

== View Minion details

You can view details about the Minion including latency and status on the Inventory page (select *Inventory* from the left navigation menu).

== Delete a location

To delete a location, follow these steps:

. Click *Locations* in the left navigation menu.
. Find the location that you want to remove and select the vertical ellipsis beside its name.
. Choose *Delete* and confirm deletion.

== Delete a Minion

If you delete your only Minion, you will no longer receive network monitoring data.

Follow these steps to delete a Minion:

. Click *Locations* in the left navigation menu.
. In the locations list, click the location with the Minion you want to delete.
. Click the vertical ellipsis beside the Minion name and click *Delete*.
+
You are prompted to confirm deletion.
. Click *Delete*.