spring:
  application:
    name: lokahi-metrics-threshold-processor

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "metrics-threshold-processor-service"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

  server:
    port: 9661

kafka:
    topics:
      threshold-rules: "metrics-threshold-rules"
      threshold-events: "metrics-threshold-event"
      create-topics:
        enabled: true
        thresholdEvent:
          name: "metrics-threshold-event"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

