name: Minion

on:
# Currently triggered by develop workflow, so this trigger is disabled for now until we can fully separate them
#  pull_request:
#    paths:
#      - 'minion/**'
  workflow_call:
    inputs:
      image:
        description: 'Name of the image to build'
        required: false
        type: string
      image-tag:
        description: 'Tag for the built image'
        required: false
        type: string
      image-registry:
        description: 'Docker image registry to tag and push to'
        required: false
        type: string

env:
  IMAGE: ${{ inputs.image || 'lokahi-minion' }}
  IMAGE_TAG: ${{ inputs.image-tag || github.sha }}
  IMAGE_REGISTRY: ${{ inputs.image-registry || 'ghcr.io' }}

jobs:
  build-and-test:
    name: Build and test - Minion
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of SonarCloud analysis

      - name: Log in to the Container registry
        
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Container registry
        
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Generate Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE }}
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Cache Maven dependencies
        uses: ./.github/actions/maven-cache
        with:
          cache-key-hash: ${{ hashFiles('minion/**/pom.xml', 'parent-pom/pom.xml', 'shared-lib/**/pom.xml') }}

      - name: Cleanup the Maven Cache
        uses: ./.github/actions/maven-cache-cleanup-project-artifacts

      - name: Build and install prerequisites
        uses: ./.github/actions/java-install-prereqs

      - name: Run maven spotless checks
        uses: ./.github/actions/maven-spotless
        with:
          working-directory: 'minion'

      - name: Build & Sonar Scan
        run: |
          mvn -B -Dstyle.color=always \
              -Pcicd,coverage,run-it \
              install \
              sonar:sonar \
              -Dapplication.docker.image=${{ steps.docker-metadata.outputs.tags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: 'minion'

      - name: Push Image
        run: docker push ${{ steps.docker-metadata.outputs.tags }}
        working-directory: 'minion'
