name: Notification Service

on:
# Currently triggered by develop workflow, so this trigger is disabled for now until we can fully separate them
#  pull_request:
#    paths:
#      - 'notifications/**'
  workflow_call:
    inputs:
      image:
        description: 'Name of the image to build'
        required: false
        type: string
      image-tag:
        description: 'Tag for the built image'
        required: false
        type: string
      image-registry:
        description: 'Docker image registry to tag and push to'
        required: false
        type: string

env:
  IMAGE: ${{ inputs.image || 'lokahi-notification' }}
  IMAGE_TAG: ${{ inputs.image-tag || github.sha }}
  IMAGE_REGISTRY: ${{ inputs.image-registry || 'ghcr.io' }}

jobs:
  build-and-test:
    name: Build and test - Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of SonarCloud analysis

      - name: Log in to the Container registry
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: docker-metadata
        uses: docker/metadata-action@v4.3.0
        with:
          images: |
            ${{ env.IMAGE_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE }}
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: ./.github/actions/maven-cache
        with:
          cache-key-hash: ${{ hashFiles('notifications/**/pom.xml', 'parent-pom/pom.xml', 'shared-lib/**/pom.xml') }}

      - name: Build and install prerequisites
        uses: ./.github/actions/java-install-prereqs

      - name: Run maven spotless checks
        uses: ./.github/actions/maven-spotless
        with:
          working-directory: 'notifications'

      - name: Jib Maven build, scan, and push
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: ./.github/actions/jib-maven-sonar
        with:
          working-directory: 'notifications'
          image: ${{ steps.docker-metadata.outputs.tags }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
